# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
