# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_inventoryapp'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('apps', models.ManyToManyField(blank=True, related_name='spaces', to='inventory.InventoryApp', verbose_name='приложение')),
            ],
            options={
                'verbose_name_plural': 'площадка',
                'verbose_name': 'площадка',
            },
        ),
    ]
