# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0002_space'),
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(blank=True, max_length=50, null=True, verbose_name='процессор')),
                ('motherboard', models.CharField(blank=True, max_length=50, null=True, verbose_name='материнская плата')),
                ('ram', models.CharField(blank=True, max_length=50, null=True, verbose_name='оперативная память')),
                ('gpu', models.CharField(blank=True, max_length=50, null=True, verbose_name='видеокарта')),
                ('lan', models.CharField(blank=True, choices=[('INTEGRATED', 'Встроенный'), ('EXTERNAL', 'Внешний (PCI)')], max_length=20, null=True, verbose_name='сетевой адаптер')),
                ('power_supply', models.CharField(blank=True, max_length=50, null=True, verbose_name='блок питания')),
                ('license_sticker', models.BooleanField(default=False, verbose_name='наклейка лицензии')),
                ('hdd', models.CharField(blank=True, default='-', max_length=50, verbose_name='жесткий диск')),
                ('os', models.CharField(blank=True, max_length=50, null=True, verbose_name='операционная система')),
                ('description', models.TextField(blank=True, null=True, verbose_name='примечание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='computers/')),
                ('is_active', models.BooleanField(default=True, verbose_name='удален?')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='space.Space', verbose_name='площадка')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('count', models.PositiveIntegerField(verbose_name='кол-во')),
                ('image', models.ImageField(blank=True, null=True, upload_to='distributions/')),
                ('is_active', models.BooleanField(default=True, verbose_name='удален?')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='space.Space', verbose_name='площадка')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('type_paper', models.CharField(choices=[('1', 'A0, A1, A2, A3, A4'), ('2', 'A0, A1, A2, A3'), ('3', 'A0, A1, A2'), ('4', 'A0, A1'), ('5', 'A3, A4'), ('6', 'A0'), ('7', 'A1'), ('8', 'A2'), ('9', 'A3'), ('10', 'A4')], max_length=50, verbose_name='формат бумаги')),
                ('size', models.CharField(help_text='например: 841мм X 175м', max_length=50, verbose_name='размеры')),
                ('count', models.PositiveIntegerField(verbose_name='кол-во')),
                ('min_count', models.PositiveIntegerField(verbose_name='минимальное кол-во')),
                ('description', models.TextField(blank=True, null=True, verbose_name='примечание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='papers/')),
                ('is_active', models.BooleanField(default=True, verbose_name='удален?')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='space.Space', verbose_name='площадка')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together=set([('name', 'space')]),
        ),
        migrations.AlterUniqueTogether(
            name='distribution',
            unique_together=set([('name', 'space')]),
        ),
    ]
