#!/bin/bash 

# установка необходимых пакетов в ubuntu
sudo apt-get -y install libldap2-dev libsasl2-dev libssl-dev

sudo apt-get -y install python3-pip
sudo pip3 install --upgrade pip
sudo pip3 install virtualenv

# создание папки для программы
sudo mkdir /opt/afii/
sudo chmod 777 /opt/afii/

git clone https://github.com/kovalewvladimir/afii.git /opt/afii
virtualenv --no-site-packages -p python3 /opt/afii/
cd /opt/afii/
source ./bin/activate
pip install -r ./requirements.txt
deactivate

cd /opt/afii/afii/
touch ./afii/private.py
echo "PRIVATE_SECRET_KEY = '&8+dl^g^+p$ih+bpmzu0)_fk06o)al$v=uio-mcoo**yh*7@d-'" > ./afii/private.py

cd /opt/afii/
source ./bin/activate
cd /opt/afii/afii/
python manage.py runserver 0.0.0.0:8000
deactivate