# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='space.Space', verbose_name='Площадка')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='storage',
            unique_together=set([('name', 'space')]),
        ),
    ]
