# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20161110_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemstorage',
            options={'verbose_name': 'единица складского учета', 'verbose_name_plural': 'единица складского учета'},
        ),
    ]
