# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 05:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20161114_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstorage',
            name='shelf',
            field=models.CharField(help_text='<стеллаж>-<ярус> например: D-1', max_length=10, validators=[django.core.validators.RegexValidator(message='стеллаж - заглавная латинская буква, ярус - цифра', regex='^[A-Z]\\-[0-9]$')], verbose_name='№ полки'),
        ),
    ]
