# Generated by Django 2.2.1 on 2019-05-24 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20161118_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='base_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_base': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='storage.Category', verbose_name='базовая категория'),
        ),
        migrations.AlterField(
            model_name='itemstorage',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_base': False}, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storage.Category', verbose_name='категория'),
        ),
    ]
