# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridge',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='zip',
            name='delete',
        ),
        migrations.AddField(
            model_name='cartridge',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Удален?'),
        ),
        migrations.AddField(
            model_name='printer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Удален?'),
        ),
        migrations.AddField(
            model_name='zip',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Удален?'),
        ),
        migrations.AlterField(
            model_name='basecartridge',
            name='base_printers',
            field=models.ManyToManyField(blank=True, related_name='base_cartridges', to='printer.BasePrinter', verbose_name='Базовый принтер'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='base_printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='printer.BasePrinter', verbose_name='Базовый принтер'),
        ),
    ]
