# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_auto_20161029_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='count_in_recycling',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='кол-во в рециклинге'),
        ),
    ]
