# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_cartridge_count_in_recycling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecartridge',
            name='recycling',
            field=models.BooleanField(default=False, help_text='заполнить поле только для "тонер-картиржа"', verbose_name='Рециклинг'),
        ),
    ]
