# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 08:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_space'),
        ('printer', '0005_auto_20161109_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='дата установки'),
        ),
        migrations.AlterUniqueTogether(
            name='cartridge',
            unique_together=set([('base_cartridge', 'space')]),
        ),
        migrations.AlterUniqueTogether(
            name='zip',
            unique_together=set([('base_zip', 'space')]),
        ),
    ]
