# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 11:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0011_auto_20161114_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='shelf',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='!!!mes!!!', regex='([A-Z]\\-[0-9]){1}')], verbose_name='№ полки'),
        ),
    ]
