# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 05:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0013_auto_20161118_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='ip',
            field=models.CharField(help_text='если принтер не сетевой, то поле заполнить значением: USB или USB-TERM(<IP>)', max_length=25, validators=[django.core.validators.RegexValidator(regex='^(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(\\.(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}$|^USB$|^USB-TERM\\((25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(\\.(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}\\)$|^\\-$')], verbose_name='IP'),
        ),
    ]
