# Generated by Django 2.2.8 on 2020-03-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0015_auto_20190524_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='service',
            field=models.CharField(blank=True, default='Нет', max_length=50, null=True, verbose_name='обслуживание'),
        ),
    ]
