# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
