# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0003_auto_20161031_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='примечание'),
        ),
    ]
