# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-16 13:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0005_auto_20170515_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='дата изменения'),
        ),
    ]
