# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(blank=True, max_length=50, null=True)),
                ('space_discription', models.TextField()),
            ],
            options={
                'db_table': 'space',
            },
        ),
    ]
