# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('type', models.CharField(choices=[('TONER', 'Тонер-картридж'), ('DRAMM', 'Драм-картридж'), ('JET', 'Струйный-картридж')], max_length=10, verbose_name='Тип картриджа')),
                ('color', models.CharField(blank=True, choices=[('BLACK', 'Черный'), ('COLOR', 'Цветной'), ('YELLOW', 'Желтый'), ('BLUE', 'Синий'), ('RED', 'Красный')], max_length=10, null=True, verbose_name='Цвет')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='BasePrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('type_printing', models.CharField(choices=[('JET', 'Струйный'), ('LASER', 'Лазер'), ('SOLID', 'Твердочернильный')], max_length=10, verbose_name='Тип принтера')),
                ('type', models.CharField(choices=[('PSC', 'Принтер, копир, сканер'), ('PRINTER', 'Принтер'), ('SCANNER', 'Сканер'), ('COPY', 'Копир'), ('PLOTTER', 'Плоттер')], max_length=10, verbose_name='Тип устройства')),
                ('color', models.CharField(choices=[('BLACK', 'Черный'), ('COLOR', 'Цветной'), ('YELLOW', 'Желтый'), ('BLUE', 'Синий'), ('RED', 'Красный')], max_length=10, verbose_name='Цвет')),
                ('info_consumables', models.URLField(blank=True, null=True, verbose_name='Информация по расходникам')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('base_cartridge', models.ManyToManyField(to='inventory.BaseCartridge', verbose_name='Картридж')),
            ],
        ),
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('base_cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.BaseCartridge', verbose_name='Картридж')),
            ],
        ),
        migrations.CreateModel(
            name='PaperSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, unique=True, verbose_name='Формат бумаги')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('base_printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.BasePrinter')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Space', verbose_name='Площадка')),
            ],
        ),
        migrations.AddField(
            model_name='baseprinter',
            name='papers',
            field=models.ManyToManyField(to='inventory.PaperSize', verbose_name='Формат бумаги'),
        ),
    ]
