# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('type', models.CharField(choices=[('T', 'Tonet'), ('D', 'Dramm')], max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BasePrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='space',
            old_name='space_discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='space_name',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='space',
            table=None,
        ),
        migrations.AddField(
            model_name='storage',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Space'),
        ),
    ]
