# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50, unique=True, verbose_name='имя')),
                ('verbose_name', models.CharField(max_length=50, verbose_name='полное имя')),
                ('view_name_url', models.CharField(max_length=50, verbose_name='view_name_url')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name_plural': 'приложения inventory',
                'verbose_name': 'приложение inventory',
            },
        ),
    ]
