# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20160913_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='sn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серийный номер'),
        ),
    ]
