# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20160920_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='hdd',
            field=models.CharField(blank=True, default='-', max_length=50, verbose_name='Жесткий диск'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='lan',
            field=models.CharField(blank=True, choices=[('INTEGRATED', 'Встроенная '), ('EXTERNAL', 'Внешняя (PCI)')], max_length=20, null=True, verbose_name='Сетевой адаптер'),
        ),
    ]
