# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20160920_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='inventory.Storage'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='distributions/'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='printers/'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='sn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серийный номер'),
        ),
    ]
