# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20160920_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseprinter',
            old_name='papers',
            new_name='type_paper',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='papers',
            new_name='type_paper',
        ),
        migrations.AlterField(
            model_name='basecartridge',
            name='color',
            field=models.CharField(blank=True, choices=[('BLACK', 'Черный'), ('COLOR', 'Цветной'), ('YELLOW', 'Желтый'), ('BLUE', 'Синий'), ('RED', 'Красный')], help_text='Заполнить поле только для "тонер-картиржа"', max_length=10, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='basecartridge',
            name='recycling',
            field=models.BooleanField(help_text='Заполнить поле только для "тонер-картиржа"', verbose_name='Рециклинг'),
        ),
    ]
