# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20160921_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='zip',
            name='min_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Минимальное кол-во'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basecartridge',
            name='type',
            field=models.CharField(choices=[('TONER', 'Тонер-картридж'), ('DRAM', 'Драм-картридж'), ('JET', 'Струйный-картридж')], max_length=10, verbose_name='Тип картриджа'),
        ),
    ]
