# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20160923_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zip',
            old_name='base_zips',
            new_name='base_zip',
        ),
    ]
