# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20160923_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='count_recycling',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Кол-во в рециклинг'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='inventory.Space', verbose_name='Площадка'),
        ),
    ]
