# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20160924_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecartridge',
            name='color',
            field=models.CharField(blank=True, choices=[('BLACK', 'Черный'), ('COLOR', 'Цветной'), ('YELLOW', 'Желтый'), ('BLUE', 'Синий'), ('RED', 'Красный')], help_text="Заполнить поле только для 'тонер-картиржа'", max_length=10, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='ip',
            field=models.CharField(help_text='Если принтер не сетевой, то поле заполнить значением: USB', max_length=15, verbose_name='IP'),
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together=set([('name', 'space')]),
        ),
    ]
