# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20160926_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterUniqueTogether(
            name='distribution',
            unique_together=set([('name', 'space')]),
        ),
        migrations.AlterUniqueTogether(
            name='storage',
            unique_together=set([('name', 'space')]),
        ),
    ]
