# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20160926_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='license_sticker',
            field=models.BooleanField(default=False, verbose_name='Наклейка лицензии'),
        ),
        migrations.AddField(
            model_name='computer',
            name='power_supply',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Блок питания'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='lan',
            field=models.CharField(blank=True, choices=[('INTEGRATED', 'Встроенный'), ('EXTERNAL', 'Внешний (PCI)')], max_length=20, null=True, verbose_name='Сетевой адаптер'),
        ),
    ]
