# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20161016_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('count', models.PositiveIntegerField(verbose_name='Кол-во')),
                ('shelf', models.CharField(max_length=10, verbose_name='№ полки')),
                ('delete', models.BooleanField(default=False, verbose_name='Удален?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_storage/')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.Cartridge')),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='base_categoty',
            new_name='base_category',
        ),
    ]
