# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20161016_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstorage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.Category'),
        ),
    ]
