# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20161016_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_base',
            field=models.BooleanField(default=False, verbose_name='Базовая категория?'),
        ),
    ]
