# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20161016_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='base_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='inventory.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
